{{ 
	standard_config(
		model_name='stg_open_sfi.',
		zone='bronze',
		materialized='ephemeral'
	)
}}

SELECT 
	accountid,
	id_email,
	id_open,
	batchid,
	"domain",
	eventdate,
	isunique,
	jobid,
	listid,
	oybaccountid,
	subscriberid,
	subscriberkey,
	triggeredsendcustomerkey,
	triggerersenddefinitionobjectid,
	ingestion_date,
	ingestion_year,
	ingestion_month,
	ingestion_day,
	execution_date,
	execution_year,
	execution_month,
	execution_day
FROM 
{{ source('comunicacoes_bronze', 'open_sfi') }}
