{{ standard_config(
	model_name='send_sfmc',
	zone='silver',
	materialized='table'
) }}

WITH base AS (
SELECT
	jobid as id,
    emailid,
    accountid,
    accountuserid,
    fromname,
    fromemail as fromaddress,
    schedtime,
    pickuptime,
    deliveredtime,
    eventid,
    ismultipart,
    jobtype,
    jobstatus,
    modifiedby,
    modifieddate,
    emailname,
    emailsubject,
    iswrapped,
    testemailaddr,
    category,
    bccemail,
    originalschedtime,
    createddate,
    characterset,
    ipaddress,
    salesforcetotalsubscribercount,
    salesforceerrorsubscribercount,
    sendtype,
    dynamicemailsubject,
    suppresstracking,
    sendclassificationtype,
    sendclassification,
    resolvelinkswithcurrentdata,
    emailsenddefinition,
    deduplicatebyemail,
    triggerersenddefinitionobjectid,
    triggeredsendcustomerkey,
    ingestion_date,
    ingestion_year,
    ingestion_month,
    ingestion_day,
    job.execution_date,
    execution_year,
    execution_month,
    execution_day,
	ROW_NUMBER() OVER (PARTITION BY jobid ORDER BY modifieddate DESC, ingestion_date DESC, RANDOM()) AS rownumber
FROM 
    {{ ref('stg_send_sfi')}}  job
)
SELECT
	id,
	emailid,
	accountid,
	accountuserid,
	fromname,
	fromaddress,
	schedtime,
	pickuptime,
	deliveredtime,
	eventid,
	ismultipart,
	jobtype,
	jobstatus,
	modifiedby,
	modifieddate,
	emailname,
	emailsubject,
	iswrapped,
	testemailaddr,
	category,
	bccemail,
	originalschedtime,
	createddate,
	characterset,
	ipaddress,
	salesforcetotalsubscribercount,
	salesforceerrorsubscribercount,
	sendtype,
	dynamicemailsubject,
	suppresstracking,
	sendclassificationtype,
	sendclassification,
	resolvelinkswithcurrentdata,
	emailsenddefinition,
	deduplicatebyemail,
	triggerersenddefinitionobjectid,
	triggeredsendcustomerkey,
	ingestion_date,
	ingestion_year,
	ingestion_month,
	ingestion_day,
	execution_date,
	execution_year,
	execution_month,
	execution_day
FROM
	base
WHERE
	rownumber = 1	

