{{ standard_config(
	model_name='sms_sfmc',
	zone='silver',
	materialized='table'
) }}

WITH base_sms AS (
SELECT
	mobilemessagetrackingid,
	subscriberid,
	subscriberkey AS id_pessoa,
	eid,
	mid,
	mobile,
	messageid,
	keywordid,
	codeid,
	conversationid,
	campaignid,
	"sent",
	delivered,
	undelivered,
	unsub,
	optin,
	optout,
	CASE
		WHEN inbound = 'True' THEN 'Inbound'
		WHEN outbound = 'True' THEN 'Outbound'
	END AS origin,
	createdatetime,
	modifieddatetime,
	actiondatetime,
	istest,
	mobilemessagerecurrenceid,
	responsetomobilemessagetrackingid,
	isvalid,
	invalidationcode,
	sendid,
	sendsplitid,
	sendsegmentid,
	sendjobid,
	sendgroupid,
	sendpersonid,
	smsstandardstatuscodeid,
	"description",
	"name" AS sms_name,
	shortcode,
	sharedkeyword,
	ordinal,
	fromname,
	jbdefinitionid,
	jbactivityid,
	smsjobid,
	ingestion_date,
	ingestion_year,
	ingestion_month,
	ingestion_day,
	execution_date,
	execution_year,
	execution_month,
	execution_day,
	ROW_NUMBER() OVER (PARTITION BY mobilemessagetrackingid
ORDER BY
	modifieddatetime DESC,
	ingestion_date DESC,
	RANDOM()) AS rownumber
FROM
	{{ ref('stg_sms_sfi') }} 
)
SELECT
	mobilemessagetrackingid,
	subscriberid,
	id_pessoa,
	eid,
	mid,
	mobile,
	messageid,
	keywordid,
	codeid,
	conversationid,
	campaignid,
	sent,
	delivered,
	undelivered,
	unsub,
	optin,
	optout,
	origin,
	createdatetime,
	modifieddatetime,
	actiondatetime,
	istest,
	mobilemessagerecurrenceid,
	responsetomobilemessagetrackingid,
	isvalid,
	invalidationcode,
	sendid,
	sendsplitid,
	sendsegmentid,
	sendjobid,
	sendgroupid,
	sendpersonid,
	smsstandardstatuscodeid,
	description,
	sms_name,
	shortcode,
	sharedkeyword,
	ordinal,
	fromname,
	jbdefinitionid,
	jbactivityid,
	smsjobid,
	ingestion_date,
	ingestion_year,
	ingestion_month,
	ingestion_day,
	execution_date,
	execution_year,
	execution_month,
	execution_day
FROM
	base_sms
WHERE
	rownumber = 1